openapi: 3.1.0
x-stoplight:
  id: i98xx6cv1u2w9
info:
  title: Payments API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /payments:
    get:
      summary: List Invoices
      tags: []
      responses: {}
      operationId: list-invoices
      parameters:
        - $ref: '#/components/parameters/sort'
        - schema:
            type: string
          in: query
          name: skip
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: ../models/invoice.yaml
        description: ''
    post:
      summary: Create Invoice
      operationId: create-invoice
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/invoice.yaml
    parameters: []
components:
  schemas: {}
  parameters:
    sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
          - created
          - updated
        default: created
