openapi: 3.1.0
x-stoplight:
  id: i98xx6cv1u2w9
info:
  title: Todos API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /todos:
    get:
      summary: List Todos
      tags: []
      responses: {}
      operationId: list-todos
      parameters:
      - name: sort
        description: Can be one of `created`, `updated`, `pushed`, `full_name`.
        in: query
        required: false
        schema:
          type: string
          enum:
          - created
          - updated
          - pushed
          - full_name
          default: created
components:
  schemas: {}
  parameters:
    sort:
      name: sort
      description: One of `created` (when the repository was starred) or `updated`
        (when it was last pushed to).
      in: query
      required: false
      schema:
        type: string
        enum:
        - created
        - updated
        default: created
